apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: word-count-pl
spec:
  vertices:
    - name: in
      scale:
        min: 1
      source:
        # An http endpoint
        http:
          # Whether to create a ClusterIP Service, defaults to false
          service: true
          # Optional bearer token auth
          # xxx examples should be self-contained and runnable by the user
    #         auth:
    #           # A secret selector pointing to the secret contains token
    #           token:
    #             name: my-secret
    #             key: my-key
    - name: cat
      scale:
        min: 1
      udf:
        container:
          image: quay.io/yhl25/nitk-workshop/word-count:stable
    - name: counter
      udf:
        container:
          # compute the sum
          image: quay.io/yhl25/nitk-workshop/word-split:stable
        groupBy:
          window:
            fixed:
              length: 5s
          keyed: true
          storage:
            emptyDir: { }
    - name: out
      scale:
        min: 1
      sink:
        # A simple log printing sink
        log: {}
  edges:
    - from: in
      to: cat
    - from: cat
      to: counter
    - from: counter
      to: out